### ISSUE TITLE
tests missing from pypi tarball

### ISSUE THREAD

**Issue by dvzrv** [click-contrib/click-help-colors#10]
Hi! I'm packaging python-click-help-colors for Arch Linux.

We're usually using the sdist tarballs from pypi.org, as they ensure uniqueness. However, in this case, the sdist release is missing the tests. As the sdist is supposed to contain the sources from which users can build the package, it should also contain the tests, so that they can validate, that click-help-colors integrates with their system python.

The directory can be added to MANIFEST.in and will then be available in the sdist tarball upon next release.

**Comment by dvzrv** [comment]
On 2nd look, I realize, that a `python setup.py sdist` should currently already do the right thing.
How was the version 0.7 sdist tarball created for pypi.org?

**Comment by r-m-n** [comment]
fixed in 0.8
